# Project information
site_name: GeoNetwork opensource
site_description: GeoNetwork catalogue for listing, searching and reviewing records.
site_dir: target/html
site_url: http://jodygarnett.github.io/core-geonetwork/

# Repository
repo_name: geonetwork/core-geonetwork
repo_url: https://github.com/geocat/core-geonetwork
edit_uri: edit/mkdocs/docs/manual/docs

# Copyright
copyright: Copyright &copy; 2001 - 2023 FAO-UN and others


extra_css:
  - stylesheets/extra.css

# Configuration
theme:
  name: material
  language: en
  custom_dir: overrides
  logo: assets/geonetwork-logo.svg
  favicon: assets/geonetwork-logo.png
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - content.action.view
    - content.action.edit
    - content.code.copy
    - content.tabs.link
    - navigation.tabs
    - navigation.tracking
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    - navigation.footer
    - announce.dismiss

# Plugins - install using: pip3 install -r requirements.txt
plugins:
  - search
  - i18n:
      docs_structure: suffix
      reconfigure_material: true
      languages:
        - locale: en
          name: English
          build: true
          default: true
          site_name: 'GeoNetwork Opensource (EN)'
        - locale: fr
          name: Français
          build: !ENV [FRENCH,true]
          site_name: 'GeoNetwork Opensource (FR)'
          site_description: Catalogue GeoNetwork pour répertorier, rechercher et examiner les enregistrements.
          nav_translations:
            Home: Home
            Search: Search
            Record: Record
            Map: Map
  - exclude:
      glob:
        - annexes/gallery/bin/README.md
# - include-markdown

# Customizations
extra:
  version:
    provider: mike
    default: stable
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/geonetwork
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/_/geonetwork
    - icon: fontawesome/solid/arrow-up-right-from-square
      link: https://geonetwork-opensource.org/
      name: GeoNetwork Website

# Extensions
# - These are carefully chosen to work with pandoc markdown support for whole document translation
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - md_in_html

# Page tree
nav:
  - index.md
  - 'Developer':
    - developer/index.md
    - developer/development/index.md
    - developer/harvesting/index.md
    - developer/mef/index.md
    - developer/release/index.md
    - developer/schemaPlugins/index.md
    - developer/settings/index.md
    - developer/userinterface/index.md
    - developer/userinterface/html5ui/index.md
    - developer/userinterface/widgets/index.md
    - developer/xml_services/index.md
    - developer/xml_services/category_xml_services.md
    - developer/xml_services/csw_services.md
    - developer/xml_services/group_xml_services.md
    - developer/xml_services/java_xml_services.md
    - developer/xml_services/login_xml_services.md
    - developer/xml_services/metadata_xml_categories.md
    - developer/xml_services/metadata_xml_insert_update_delete.md
    - developer/xml_services/metadata_xml_ownership.md
    - developer/xml_services/metadata_xml_privileges.md
    - developer/xml_services/metadata_xml_processing.md
    - developer/xml_services/metadata_xml_relations.md
    - developer/xml_services/metadata_xml_search_retrieve.md
    - developer/xml_services/metadata_xml_select.md
    - developer/xml_services/metadata_xml_status.md
    - developer/xml_services/metadata_xml_validation.md
    - developer/xml_services/metadata_xml_versioning.md
    - developer/xml_services/schema_services.md
    - developer/xml_services/services_calling.md
    - developer/xml_services/services_download.md
    - developer/xml_services/services_harvesting.md
    - developer/xml_services/services_mef.md
    - developer/xml_services/services_site_info_forwarding.md
    - developer/xml_services/system_configuration.md
    - developer/xml_services/user_xml_services.md
  - 'User':
    - users/index.md
    - users/faq.md
    - users/glossary.md
    - users/preface.md
    - users/admin/index.md
    - users/admin/advanced-configuration/index.md
    - users/admin/authentication/index.md
    - users/admin/configuration/index.md
    - users/admin/csw-configuration/index.md
    - users/admin/localization/index.md
    - users/admin/monitoring/index.md
    - users/admin/usersandgroups/index.md
    - users/appendix/foss4g/index.md
    - users/appendix/glossary_of_metadata/index.md
    - users/appendix/iso_topic_categories/index.md
    - users/features/index.md
    - users/features/multilingual/index.md
    - users/features/search_statistics/index.md
    - users/features/thesaurus/index.md
    - users/features/user-self-registration/index.md
    - users/managing_metadata/index.md
    - users/managing_metadata/export/index.md
    - users/managing_metadata/formatter/index.md
    - users/managing_metadata/fragments/index.md
    - users/managing_metadata/harvesting/index.md
    - users/managing_metadata/harvesting/common_categories.md
    - users/managing_metadata/harvesting/common_notes.md
    - users/managing_metadata/harvesting/common_options.md
    - users/managing_metadata/harvesting/common_privileges.md
    - users/managing_metadata/harvesting/csw/index.md
    - users/managing_metadata/harvesting/geoPREST/index.md
    - users/managing_metadata/harvesting/gn/index.md
    - users/managing_metadata/harvesting/gn2.0/index.md
    - users/managing_metadata/harvesting/localfilesystem/index.md
    - users/managing_metadata/harvesting/oaipmh/index.md
    - users/managing_metadata/harvesting/ogcwxs/index.md
    - users/managing_metadata/harvesting/sde/index.md
    - users/managing_metadata/harvesting/thredds/index.md
    - users/managing_metadata/harvesting/webdav/index.md
    - users/managing_metadata/harvesting/wfs-getfeatures/index.md
    - users/managing_metadata/harvesting/z3950/index.md
    - users/managing_metadata/import/index.md
    - users/managing_metadata/import/importActions.md
    - users/managing_metadata/massive_replace/index.md
    - users/managing_metadata/ownership/index.md
    - users/managing_metadata/processing/index.md
    - users/managing_metadata/schemas/index.md
    - users/managing_metadata/status/index.md
    - users/managing_metadata/templates/index.md
    - users/managing_metadata/versioning/index.md
    - users/quickstartguide/index.md
    - users/quickstartguide/geographic_management/index.md
    - users/quickstartguide/getting_started/index.md
    - users/quickstartguide/installing/index.md
    - users/quickstartguide/metadata_concepts/index.md
    - users/quickstartguide/new_metadata/index.md
    - users/quickstartguide/new_metadata/linking.md
    - users/quickstartguide/newfeatures/index.md
    - users/quickstartguide/viewing/index.md