name: Documentation

on:
  push:
    branches:
      - 3.12.x
    paths:
      - "docs/manual/**"
  pull_request:
    branches:
      - 3.12.x
    paths:
      - "docs/manual/**"
  workflow_dispatch:

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GeoNetwork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: mkdocs install
        run: pip install --upgrade pip && pip install -r docs/manual/requirements.txt
      - name: git configuration
        run: git config user.name 'github-actions[bot]' && git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: build docs without publishing them
        if: ${{ github.event_name == 'pull_request' }}
        working-directory: docs/manual
        run: |
          mike deploy --title "3.12" --alias-type=copy --update-aliases 3.12 maintenance
      - name: deploy maintenance docs to gh-pages branch
        if: ${{ github.event_name != 'pull_request' }}
        working-directory: docs/manual
        run: |
          mike deploy --push --title "3.12" --alias-type=copy --update-aliases 3.12 maintenance
