name: Linux GitHub CI

on: [pull_request,push,workflow_dispatch]

env:
  MAVEN_OPTS: -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3 -Xmx512m -Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss,SSS
  TAKARI_SMART_BUILDER_VERSION: 0.6.1

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            jdk: 11
    steps:
    - uses: actions/checkout@v3
      with:
        # 500 commits, set to 0 to get all
        fetch-depth: 500
        submodules: 'recursive'
    - name: Set up JDK
      uses: actions/setup-java@v3.12.0
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.jdk }}
        cache: 'maven'
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4
      with:
        maven-version: 3.6.3
    - name: Build with Maven
      run: mvn -B -V install -DskipTests=true -Dmaven.javadoc.skip=true
    - name: Remove SNAPSHOT jars from repository
      run: |
        find ~/.m2/repository -name "*SNAPSHOT*" -type d | xargs rm -rf {}
    - name: Remove Schema 3.8 jars from repository
      run: |
        find ~/.m2/repository -name "*3.8*" -type d | xargs rm -rf {}

  QA:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        # 500 commits, set to 0 to get all
        fetch-depth: 500
        submodules: 'recursive'
    - name: Set up JDK
      uses: actions/setup-java@v3.12.0
      with:
        distribution: 'temurin'
        java-version: 11
        cache: 'maven'
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4
      with:
        maven-version: 3.6.3
    - name: Test with maven
      run: |
        mvn resources:resources@copy-index-schema-to-source -f web
        mvn -B -V -fae verify -Pit
    - name: Remove SNAPSHOT jars from repository
      run: |
        find ~/.m2/repository -name "*SNAPSHOT*" -type d | xargs rm -rf {}
    - name: Remove Schema 3.8 jars from repository
      run: |
        find ~/.m2/repository -name "*3.8*" -type d | xargs rm -rf {}
