name: Linux GitHub CI

on: [pull_request,push,workflow_dispatch]

env:
  MAVEN_OPTS: -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3 -Xmx512m -Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss,SSS -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
  TAKARI_SMART_BUILDER_VERSION: 0.6.1

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            jdk: 11
    steps:
    - uses: actions/checkout@v4
      with:
        # 500 commits, set to 0 to get all
        fetch-depth: 500
        submodules: 'recursive'
        show-progress: 'false'
    - name: Set up JDK
      uses: actions/setup-java@v4.2.1
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.jdk }}
        cache: 'maven'
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - name: mkdocs install
      working-directory: docs/manual
      run: pip install --upgrade pip && pip install -r requirements.txt
    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: 3.8.3
    - name: Build with Maven
      run: |
        mvn -B -ntp -V install -DskipTests=true -Dmaven.javadoc.skip=true -Drelease -Pwith-doc
    - name: Remove SNAPSHOT jars from repository
      run: |
        find ~/.m2/repository -name "*SNAPSHOT*" -type d | xargs rm -rf {}

  QA:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with:
        # 500 commits, set to 0 to get all
        fetch-depth: 500
        submodules: 'recursive'
        show-progress: 'false'
    - name: Set up JDK
      uses: actions/setup-java@v4.2.1
      with:
        distribution: 'temurin'
        java-version: 11
        cache: 'maven'
    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: 3.8.3
    - name: Test with maven
      run: |
        mvn -B resources:resources@copy-index-schema-to-source -f web
        mvn -B -ntp -V -fae verify -Drelesae -Pit
    - name: Remove SNAPSHOT jars from repository
      run: |
        find ~/.m2/repository -name "*SNAPSHOT*" -type d | xargs rm -rf {}
