# This job sends the maven dependency tree of the project to Github
# for further security analysis.

name: "MavenDepTreeSubmission"

on:
  push:
    branches: [ 4.2.x ]
  schedule:
    - cron: '44 22 * * 5'

jobs:
  update-maven-dep-tree:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          show-progress: 'false'

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 8
          # Java distribution. See the list of supported distributions in README file
          distribution: temurin
          # The package type (jdk, jre, jdk+fx, jre+fx)
          java-package: jdk
          cache: maven

      - name: Submit Dependency Snapshot
        uses: advanced-security/maven-dependency-submission-action@v4
